const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const provinces=['کندهار','کابل','هرات','بلخ','ننګرهار','هلمند','غزني','فراه','نیمروز','زابل','ارزګان','پکتیا','پکتیکا','خوست','کندز','تخار','بدخشان','بغلان','سمنګان','سرپل','جوزجان','فاریاب','بادغیس','غور','دایکندي','بامیان','پروان','کاپیسا','پنجشېر','لغمان','کونړ','نورستان','لوګر','میدان وردګ'];
const demoUser={name:'احمد جان',phone:'0700000000',pin:'1234',approved:true};
let currentUser=null,editingPhoto='';
const orders=()=>JSON.parse(localStorage.getItem('ifc_orders')||'[]');
const saveOrders=v=>localStorage.setItem('ifc_orders',JSON.stringify(v));
function view(id){$$('.view').forEach(v=>v.classList.remove('active'));$('#'+id).classList.add('active')}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2400)}
$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.toggle('active',x===b));$$('.form').forEach(f=>f.classList.toggle('active',f.id===b.dataset.tab+'Form'))});
$('#registerForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);const pending=JSON.parse(localStorage.getItem('ifc_pending')||'[]');pending.push({name:f.get('name'),phone:f.get('phone'),pin:f.get('pin'),createdAt:new Date().toISOString(),approved:false});localStorage.setItem('ifc_pending',JSON.stringify(pending));view('pendingView')};
$('#loginForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),pending=JSON.parse(localStorage.getItem('ifc_pending')||'[]');currentUser=[demoUser,...pending].find(u=>u.phone.replace(/\s/g,'')===f.get('phone').replace(/\s/g,'')&&u.pin===f.get('pin'));if(!currentUser)return toast('شمېره یا PIN سم نه دی');if(!currentUser.approved)return toast('ستاسې حساب لا تر اوسه تایید شوی نه دی');openApp()};
function openApp(){view('appView');$('#bottomNav').classList.remove('hidden');$('#logoutBtn').classList.remove('hidden');$('#userName').textContent=currentUser.name;$('.avatar').textContent=currentUser.name[0];render()}
$('#logoutBtn').onclick=()=>{currentUser=null;view('authView');$('#bottomNav').classList.add('hidden');$('#logoutBtn').classList.add('hidden')};
provinces.forEach(p=>$('#orderForm select').add(new Option(p,p)));
function openOrder(id){const form=$('#orderForm');form.reset();form.id.value='';editingPhoto='';$('#photoPreview').style.display='none';$('.product-photo span').style.display='block';$('#dialogKicker').textContent='نوی آرډر';$('#dialogTitle').textContent='د جنس معلومات';if(id){const o=orders().find(x=>x.id===id);Object.keys(o).forEach(k=>{if(form.elements[k])form.elements[k].value=o[k]});editingPhoto=o.photo||'';if(editingPhoto){$('#photoPreview').src=editingPhoto;$('#photoPreview').style.display='block';$('.product-photo span').style.display='none'}$('#dialogKicker').textContent='آرډر اصلاح کړئ';$('#dialogTitle').textContent=o.product}$('#orderDialog').showModal()}
$('#addOrderTop').onclick=$('#addOrderNav').onclick=()=>openOrder();$('#closeDialog').onclick=()=>$('#orderDialog').close();
$('#orderForm [name=photo]').onchange=e=>{const file=e.target.files[0];if(!file)return;const r=new FileReader();r.onload=()=>{editingPhoto=r.result;$('#photoPreview').src=r.result;$('#photoPreview').style.display='block';$('.product-photo span').style.display='none'};r.readAsDataURL(file)};
$('#orderForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),id=f.get('id')||crypto.randomUUID();if(!editingPhoto)return toast('د جنس عکس واخلئ یا انتخاب یې کړئ');let list=orders();const item={id,owner:currentUser.phone,product:f.get('product'),customerPhone:f.get('customerPhone'),province:f.get('province'),quantity:Number(f.get('quantity')),address:f.get('address'),price:Number(f.get('price')),photo:editingPhoto,status:'ثبت شوی',createdAt:list.find(x=>x.id===id)?.createdAt||new Date().toISOString()};const at=list.findIndex(x=>x.id===id);at>=0?list[at]=item:list.unshift(item);saveOrders(list);$('#orderDialog').close();render();toast(at>=0?'آرډر اصلاح شو':'آرډر په بریالیتوب ثبت شو')};
function render(){const list=orders().filter(o=>o.owner===currentUser.phone);$('#weekOrders').textContent=list.length;$('#weekTotal').textContent=list.reduce((s,o)=>s+o.price,0).toLocaleString('fa-AF');$('#emptyState').style.display=list.length?'none':'block';$('#ordersList').innerHTML=list.map(o=>`<article class="order-card"><img src="${o.photo}" alt="${o.product}"><div class="order-main"><div class="order-top"><h4>${o.product}</h4><span class="badge">${o.status}</span></div><div class="order-meta"><span>📍 ${o.province}</span><span>📦 ${o.quantity} دانې</span><span>☎ ${o.customerPhone}</span></div><div class="order-foot"><strong>${o.price.toLocaleString('fa-AF')} ؋</strong><button class="edit-btn" data-edit="${o.id}">اصلاح ✎</button></div></div></article>`).join('');$$('[data-edit]').forEach(b=>b.onclick=()=>openOrder(b.dataset.edit))}
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
