const SUPABASE_URL='https://ejsittccdckyiphiazwr.supabase.co';
const SUPABASE_KEY='sb_publishable_OMeUCfZRbVA3lzdRty2wuw_t1Q5_xEc';
const db=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const provinces=['کندهار','کابل','هرات','بلخ','ننګرهار','هلمند','غزني','فراه','نیمروز','زابل','ارزګان','پکتیا','پکتیکا','خوست','کندز','تخار','بدخشان','بغلان','سمنګان','سرپل','جوزجان','فاریاب','بادغیس','غور','دایکندي','بامیان','پروان','کاپیسا','پنجشېر','لغمان','کونړ','نورستان','لوګر','میدان وردګ'];
const roleNames={admin:'اډمین',agent:'شاګرد',dispatcher:'د لېږلو مسؤل'};
const statusNames={registered:'ثبت شوی',sent:'ولېږل شو',delivered:'تسلیم شو'};
let session=null,profile=null,currentOrders=[],editingPhoto=null;

function show(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===id))}
function toast(msg){$('#toast').textContent=msg;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2800)}
function busy(form,on){const b=form.querySelector('button[type=submit]');if(b)b.disabled=on}
function phone(v){let p=(v||'').replace(/\D/g,'');if(p.startsWith('0093'))p='0'+p.slice(4);else if(p.startsWith('93'))p='0'+p.slice(2);if(p.length===9&&!p.startsWith('0'))p='0'+p;return p}
function emailFor(p){return `${p}@ishaqzada.delivery`}
function passwordFor(p,pin){return `IFC!${pin}${p.slice(-2)}`}
function ext(file){return (file.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'')}
function weekStart(){const d=new Date();const day=(d.getDay()+1)%7;d.setHours(0,0,0,0);d.setDate(d.getDate()-day);return d.toISOString()}

$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.toggle('active',x===b));$$('#authView .form').forEach(f=>f.classList.toggle('active',f.id===b.dataset.auth))});
$$('.nav').forEach(b=>b.onclick=()=>{show(b.dataset.view);if(b.dataset.view==='adminView')loadUsers();if(b.dataset.view==='reportView')loadReport()});
provinces.forEach(p=>$('#orderForm select').add(new Option(p,p)));

$('#registerForm').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,f=new FormData(form),p=phone(f.get('phone')),pin=f.get('pin');if(!/^07\d{8}$/.test(p))return toast('د موبایل شمېره سمه ولیکئ');busy(form,true);try{const {data,error}=await db.auth.signUp({email:emailFor(p),password:passwordFor(p,pin),options:{data:{full_name:f.get('name').trim(),phone:p}}});if(error)throw error;if(!data.session)throw new Error('د Email confirmation بندول پکار دي');const uid=data.user.id,photo=f.get('profilePhoto'),photoPath=`${uid}/profile.${ext(photo)}`;const up=await db.storage.from('identity-docs').upload(photoPath,photo,{upsert:true});if(up.error)throw up.error;const {error:rpcError}=await db.rpc('set_my_identity_paths',{p_tazkira_path:null,p_selfie_path:photoPath});if(rpcError)throw rpcError;profile=await getProfile();route()}catch(err){toast(errorText(err))}finally{busy(form,false)}};

$('#loginForm').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,f=new FormData(form),p=phone(f.get('phone'));busy(form,true);try{const {data,error}=await db.auth.signInWithPassword({email:emailFor(p),password:passwordFor(p,f.get('pin'))});if(error)throw error;session=data.session;profile=await getProfile();route()}catch(err){toast('شمېره یا PIN سم نه دی')}finally{busy(form,false)}};
$('#logoutBtn').onclick=$('#pendingLogout').onclick=async()=>{await db.auth.signOut();session=null;profile=null;$('#bottomNav').classList.add('hidden');$('#logoutBtn').classList.add('hidden');show('authView')};

async function getProfile(){const {data,error}=await db.from('profiles').select('*').single();if(error)throw error;return data}
async function boot(){const {data}=await db.auth.getSession();session=data.session;if(session){try{profile=await getProfile();route()}catch{await db.auth.signOut();show('authView')}}else show('authView')}
function route(){if(!profile)return show('authView');if(profile.status!=='approved'){show('pendingView');$('#logoutBtn').classList.remove('hidden');return}$('#bottomNav').classList.remove('hidden');$('#logoutBtn').classList.remove('hidden');$('#adminNav').classList.toggle('hidden',profile.role!=='admin');$('#newOrderBtn').classList.toggle('hidden',profile.role!=='agent');$('#userName').textContent=profile.full_name;$('#avatarFallback').textContent=profile.full_name?.[0]||'ا';$('#avatar').classList.remove('has-photo');if(profile.selfie_path)signed('identity-docs',profile.selfie_path).then(url=>{if(url){$('#avatarImg').src=url;$('#avatar').classList.add('has-photo')}});$('#roleBadge').textContent=roleNames[profile.role];$('#ordersTitle').textContent=profile.role==='agent'?'زما وروستي آرډرونه':'ټول وروستي آرډرونه';show('homeView');loadOrders()}

async function loadOrders(){let q=db.from('orders').select('*,profiles!orders_created_by_fkey(full_name,phone)').order('created_at',{ascending:false});if(profile.role==='agent')q=q.eq('created_by',profile.id);const {data,error}=await q;if(error)return toast(error.message);currentOrders=data||[];renderOrders();renderStats()}
async function signed(bucket,path){if(!path)return '';const {data}=await db.storage.from(bucket).createSignedUrl(path,900);return data?.signedUrl||''}
async function renderOrders(){const box=$('#ordersList');box.innerHTML='';$('#ordersEmpty').style.display=currentOrders.length?'none':'block';for(const o of currentOrders){const url=await signed('order-photos',o.photo_path);const canEdit=profile.role==='agent'&&o.created_by===profile.id&&o.status==='registered';const canMove=profile.role==='dispatcher'&&o.status==='registered';const action=o.province==='کندهار'?'تسلیم شو':'ولېږل شو';box.insertAdjacentHTML('beforeend',`<article class="order-card"><img src="${url}" alt="${escapeHtml(o.product_name)}"><div class="order-main"><div class="order-top"><h4>${escapeHtml(o.product_name)}</h4><span class="badge ${o.status}">${statusNames[o.status]}</span></div><div class="order-meta"><span>📍 ${o.province}</span><span>📦 ${o.quantity}</span><span>☎ ${escapeHtml(o.customer_phone)}</span>${profile.role!=='agent'?`<span>👤 ${escapeHtml(o.profiles?.full_name||'')}</span>`:''}</div><div class="order-foot"><strong>${Number(o.price).toLocaleString('fa-AF')} ؋</strong><div class="order-actions">${canEdit?`<button class="small-btn" data-edit="${o.id}">اصلاح</button>`:''}${canMove?`<button class="small-btn action" data-move="${o.id}">${action}</button>`:''}</div></div></div></article>`)}$$('[data-edit]').forEach(b=>b.onclick=()=>openOrder(b.dataset.edit));$$('[data-move]').forEach(b=>b.onclick=()=>advance(b.dataset.move))}
function renderStats(){const ws=weekStart(),list=currentOrders.filter(o=>o.created_at>=ws);$('#weekCount').textContent=list.length.toLocaleString('fa-AF');$('#weekMoney').textContent=list.reduce((s,o)=>s+Number(o.price),0).toLocaleString('fa-AF')}

$('#newOrderBtn').onclick=()=>openOrder();$('#closeOrder').onclick=()=>$('#orderDialog').close();
function openOrder(id){const f=$('#orderForm');f.reset();f.id.value='';editingPhoto=null;$('#photoPreview').style.display='none';$('.product-photo span').style.display='block';$('#orderKicker').textContent='نوی آرډر';if(id){const o=currentOrders.find(x=>x.id===id);for(const k of ['id','product_name','customer_phone','province','quantity','address','price'])f.elements[k].value=o[k];editingPhoto=o.photo_path;$('#orderKicker').textContent='آرډر اصلاح کړئ';signed('order-photos',o.photo_path).then(url=>{if(url){$('#photoPreview').src=url;$('#photoPreview').style.display='block';$('.product-photo span').style.display='none'}})}$('#orderDialog').showModal()}
$('#orderForm [name=photo]').onchange=e=>{const file=e.target.files[0];if(!file)return;const url=URL.createObjectURL(file);$('#photoPreview').src=url;$('#photoPreview').style.display='block';$('.product-photo span').style.display='none'};
$('#orderForm').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,f=new FormData(form),id=f.get('id'),file=f.get('photo');if(!id&&(!file||!file.size))return toast('د جنس عکس واخلئ');busy(form,true);try{let photoPath=editingPhoto;if(file&&file.size){photoPath=`${profile.id}/${crypto.randomUUID()}.${ext(file)}`;const {error}=await db.storage.from('order-photos').upload(photoPath,file,{upsert:false});if(error)throw error}const payload={product_name:f.get('product_name').trim(),customer_phone:f.get('customer_phone').trim(),province:f.get('province'),quantity:Number(f.get('quantity')),address:f.get('address').trim(),price:Number(f.get('price')),photo_path:photoPath};const result=id?await db.from('orders').update(payload).eq('id',id):await db.from('orders').insert(payload);if(result.error)throw result.error;$('#orderDialog').close();toast(id?'آرډر اصلاح شو':'آرډر ثبت شو');loadOrders()}catch(err){toast(errorText(err))}finally{busy(form,false)}};
async function advance(id){const o=currentOrders.find(x=>x.id===id),next=o.province==='کندهار'?'delivered':'sent';const {error}=await db.rpc('advance_order',{p_order_id:id,p_new_status:next});if(error)return toast(errorText(error));toast(statusNames[next]);loadOrders()}

async function loadUsers(){const {data,error}=await db.from('profiles').select('*').order('created_at',{ascending:false});if(error)return toast(error.message);const pending=data.filter(u=>u.status==='pending'),approved=data.filter(u=>u.status==='approved'&&u.role!=='admin');$('#pendingCount').textContent=pending.length.toLocaleString('fa-AF');$('#usersEmpty').style.display=pending.length?'none':'block';$('#pendingUsers').innerHTML='';for(const u of pending)$('#pendingUsers').insertAdjacentHTML('beforeend',await userCard(u,true));$('#approvedUsers').innerHTML='';for(const u of approved)$('#approvedUsers').insertAdjacentHTML('beforeend',await userCard(u,false));$$('[data-user-action]').forEach(b=>b.onclick=()=>userAction(b.dataset.uid,b.dataset.userAction))}
async function userCard(u,isPending){const photoUrl=await signed('identity-docs',u.selfie_path);return `<article class="user-card"><div class="user-top"><div class="user-identity">${photoUrl?`<img class="user-photo" src="${photoUrl}" alt="${escapeHtml(u.full_name)}">`:''}<div><h4>${escapeHtml(u.full_name)}</h4><p>☎ ${u.phone} • ${roleNames[u.role]}</p></div></div><span class="badge">${isPending?'انتظار':'تایید'}</span></div><div class="user-actions">${isPending?`<button class="approve" data-uid="${u.id}" data-user-action="agent">د شاګرد په توګه تایید</button><button class="dispatch" data-uid="${u.id}" data-user-action="dispatcher">د لېږونکي په توګه تایید</button><button class="reject" data-uid="${u.id}" data-user-action="reject">رد</button>`:`<button class="approve" data-uid="${u.id}" data-user-action="agent">شاګرد</button><button class="dispatch" data-uid="${u.id}" data-user-action="dispatcher">لېږونکی</button><button class="reject" data-uid="${u.id}" data-user-action="reject">بندول</button>`}</div></article>`}
async function userAction(uid,action){const args={p_user_id:uid,p_status:action==='reject'?'rejected':'approved',p_role:action==='reject'?'agent':action};const {error}=await db.rpc('admin_set_user',{...args});if(error)return toast(errorText(error));toast('حساب تازه شو');loadUsers()}

$('#refreshBtn').onclick=loadReport;
async function loadReport(){const {data,error}=await db.rpc('weekly_report');if(error)return toast(errorText(error));const rows=data||[],orders=rows.reduce((s,r)=>s+Number(r.order_count),0),money=rows.reduce((s,r)=>s+Number(r.total_amount),0),sent=rows.reduce((s,r)=>s+Number(r.completed_count),0);$('#reportSummary').innerHTML=`<article><strong>${orders.toLocaleString('fa-AF')}</strong><span>ټول آرډرونه</span></article><article><strong>${money.toLocaleString('fa-AF')}</strong><span>ټولې افغانۍ</span></article><article><strong>${sent.toLocaleString('fa-AF')}</strong><span>لېږل/تسلیم</span></article>`;$('#reportUsers').innerHTML=rows.map(r=>`<div class="report-row"><div><b>${escapeHtml(r.full_name)}</b><br><small>${roleNames[r.role]}</small></div><b>${Number(r.order_count).toLocaleString('fa-AF')} آرډر</b><b>${Number(r.total_amount).toLocaleString('fa-AF')} ؋</b></div>`).join('')||'<div class="empty">راپور نشته</div>'}
function escapeHtml(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function errorText(e){const m=e?.message||String(e);if(m.includes('already registered'))return 'دا موبایل شمېره مخکې ثبت شوې';if(m.includes('row-level security'))return 'اجازه نشته؛ د اډمین سره اړیکه ونیسئ';return m}
let installPrompt=null;
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e});
$('#installBtn').onclick=async()=>{if(installPrompt){installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;return}$('#installDialog').showModal()};
$('#closeInstall').onclick=$('#installOk').onclick=()=>$('#installDialog').close();
if(window.matchMedia('(display-mode: standalone)').matches||navigator.standalone)$('#installBtn').classList.add('hidden');
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
boot();
