const enc=new TextEncoder();
const json=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json;charset=UTF-8',...headers}});
const err=(m,s=400)=>json({error:m},s);
const id=()=>crypto.randomUUID();
const now=()=>new Date().toISOString();
const b64=a=>btoa(String.fromCharCode(...new Uint8Array(a))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
async function sha(s){return b64(await crypto.subtle.digest('SHA-256',enc.encode(s)))}
async function pinHash(pin,salt){
  const key=await crypto.subtle.importKey('raw',enc.encode(pin),'PBKDF2',false,['deriveBits']);
  const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt:enc.encode(salt),iterations:120000,hash:'SHA-256'},key,256);
  return b64(bits);
}
function bearer(req){const h=req.headers.get('authorization')||'';return h.startsWith('Bearer ')?h.slice(7):''}
async function auth(req,env){const t=bearer(req);if(!t)return null;const h=await sha(t);return await env.DB.prepare(`SELECT u.* FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>?`).bind(h,now()).first()}
async function requireUser(req,env){const u=await auth(req,env);if(!u||u.status==='rejected')throw {status:401,message:'لومړی حساب ته ننوځئ'};return u}
async function requireAdmin(req,env){const u=await requireUser(req,env);if(u.role!=='admin'||u.status!=='approved')throw {status:403,message:'اجازه نشته'};return u}
async function parseInput(req){try{const ct=req.headers.get('content-type')||'';if(ct.includes('application/json')){const o=await req.json();return {get:k=>o?.[k]??''}}return await req.formData()}catch(_){throw {status:400,message:'معلومات سم نه دي'}}}
function validPhone(p){return /^07\d{8}$/.test(p||'')}
function validPin(p){return /^\d{4}$/.test(p||'')}
function dayKey(iso){const d=new Date(new Date(iso).getTime()+(270-360)*60000);return `${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,'0')}-${String(d.getUTCDate()).padStart(2,'0')}`}
async function ensureSystem(env){
 await env.DB.batch([
  env.DB.prepare(`CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY NOT NULL,full_name TEXT NOT NULL,phone TEXT NOT NULL UNIQUE,pin_hash TEXT NOT NULL,pin_salt TEXT NOT NULL,role TEXT DEFAULT 'agent' NOT NULL,status TEXT DEFAULT 'pending' NOT NULL,selfie_path TEXT,created_at TEXT NOT NULL)`),
  env.DB.prepare(`CREATE TABLE IF NOT EXISTS sessions (token_hash TEXT PRIMARY KEY NOT NULL,user_id TEXT NOT NULL,expires_at TEXT NOT NULL)`),
  env.DB.prepare(`CREATE TABLE IF NOT EXISTS login_attempts (phone TEXT NOT NULL,created_at TEXT NOT NULL)`),
  env.DB.prepare(`CREATE TABLE IF NOT EXISTS orders (id TEXT PRIMARY KEY NOT NULL,product_name TEXT NOT NULL,customer_phone TEXT NOT NULL,province TEXT NOT NULL,quantity INTEGER NOT NULL,address TEXT NOT NULL,price INTEGER NOT NULL,photo_path TEXT NOT NULL DEFAULT '',status TEXT DEFAULT 'registered' NOT NULL,created_by TEXT NOT NULL,created_at TEXT NOT NULL,processed_at TEXT)`),
  env.DB.prepare(`CREATE TABLE IF NOT EXISTS app_meta (key TEXT PRIMARY KEY NOT NULL,value TEXT NOT NULL)`)
 ]);
 const done=await env.DB.prepare("SELECT value FROM app_meta WHERE key='admin_bootstrap_v2'").first();
 if(!done){
  const phone='0700426319',pin='1111',salt=id(),h=await pinHash(pin,salt),existing=await env.DB.prepare('SELECT id FROM users WHERE phone=?').bind(phone).first();
  if(existing) await env.DB.prepare("UPDATE users SET full_name='اډمین',pin_hash=?,pin_salt=?,role='admin',status='approved',selfie_path=NULL WHERE id=?").bind(h,salt,existing.id).run();
  else await env.DB.prepare("INSERT INTO users(id,full_name,phone,pin_hash,pin_salt,role,status,selfie_path,created_at) VALUES(?,?,?,?,?,'admin','approved',NULL,?)").bind(id(),'اډمین',phone,h,salt,now()).run();
  await env.DB.prepare("INSERT OR REPLACE INTO app_meta(key,value) VALUES('admin_bootstrap_v2','done')").run();
 }
}
async function api(req,env,path){
 await ensureSystem(env);
 if(path==='/api/setup'&&req.method==='GET')return json({ready:true});
 if(path==='/api/register'&&req.method==='POST'){const f=await parseInput(req),name=String(f.get('name')||'').trim(),phone=String(f.get('phone')||''),pin=String(f.get('pin')||'');if(!name)return err('بشپړ نوم ولیکئ');if(!validPhone(phone))return err('د موبایل شمېره سمه ولیکئ');if(!validPin(pin))return err('څلور عددي PIN ولیکئ');if(await env.DB.prepare('SELECT id FROM users WHERE phone=?').bind(phone).first())return err('دا موبایل شمېره مخکې ثبت شوې ده');const uid=id(),salt=id(),h=await pinHash(pin,salt);await env.DB.prepare(`INSERT INTO users(id,full_name,phone,pin_hash,pin_salt,role,status,selfie_path,created_at) VALUES(?,?,?,?,?,'agent','pending',NULL,?)`).bind(uid,name,phone,h,salt,now()).run();return json({ok:true})}
 if(path==='/api/login'&&req.method==='POST'){const {phone,pin}=await req.json();if(!validPhone(phone)||!validPin(String(pin)))return err('موبایل شمېره یا PIN ناسم دی',401);const cutoff=new Date(Date.now()-15*60000).toISOString();const attempts=await env.DB.prepare('SELECT COUNT(*) AS n FROM login_attempts WHERE phone=? AND created_at>?').bind(phone,cutoff).first();if(Number(attempts?.n||0)>=8)return err('ډېرې هڅې شوې؛ ۱۵ دقیقې وروسته بیا کوښښ وکړئ',429);const u=await env.DB.prepare('SELECT * FROM users WHERE phone=?').bind(phone).first();if(!u||await pinHash(String(pin),u.pin_salt)!==u.pin_hash){await env.DB.prepare('INSERT INTO login_attempts(phone,created_at) VALUES(?,?)').bind(phone,now()).run();return err('موبایل شمېره یا PIN ناسم دی',401)}await env.DB.prepare('DELETE FROM login_attempts WHERE phone=?').bind(phone).run();if(u.status==='rejected')return err('ستاسې حساب بند شوی دی',403);const token=b64(crypto.getRandomValues(new Uint8Array(32))),th=await sha(token),exp=new Date(Date.now()+30*864e5).toISOString();await env.DB.prepare('DELETE FROM sessions WHERE user_id=?').bind(u.id).run();await env.DB.prepare('INSERT INTO sessions(token_hash,user_id,expires_at) VALUES(?,?,?)').bind(th,u.id,exp).run();return json({ok:true,token})}
 if(path==='/api/logout'&&req.method==='POST'){const t=bearer(req);if(t)await env.DB.prepare('DELETE FROM sessions WHERE token_hash=?').bind(await sha(t)).run();return json({ok:true})}
 if(path==='/api/me'){const u=await requireUser(req,env);delete u.pin_hash;delete u.pin_salt;return json({profile:u})}
 if(path==='/api/orders'&&req.method==='GET'){const u=await requireUser(req,env);if(u.status!=='approved')return err('حساب لا نه دی تایید شوی',403);const url=new URL(req.url),off=Math.max(0,Number(url.searchParams.get('offset')||0)),lim=Math.min(50,Math.max(1,Number(url.searchParams.get('limit')||20)));let rs;if(u.role==='agent')rs=await env.DB.prepare(`SELECT o.*,u.full_name creator_name FROM orders o JOIN users u ON u.id=o.created_by WHERE o.created_by=? ORDER BY o.created_at DESC LIMIT ? OFFSET ?`).bind(u.id,lim+1,off).all();else rs=await env.DB.prepare(`SELECT o.*,u.full_name creator_name FROM orders o JOIN users u ON u.id=o.created_by ORDER BY o.created_at DESC LIMIT ? OFFSET ?`).bind(lim+1,off).all();return json({orders:rs.results.slice(0,lim),hasMore:rs.results.length>lim})}
 if(path==='/api/orders'&&req.method==='POST'){const u=await requireUser(req,env);if(u.role!=='agent'||u.status!=='approved')return err('یوازې شاګرد جنس ثبتولی شي',403);const f=await parseInput(req),oid=String(f.get('id')||''),name=String(f.get('product_name')||'').trim(),cp=String(f.get('customer_phone')||'').trim(),province=String(f.get('province')||''),qty=Number(f.get('quantity')),address=String(f.get('address')||'').trim(),price=Number(f.get('price'));if(!name||!cp||!province||!address||!Number.isSafeInteger(qty)||qty<1||!Number.isSafeInteger(price)||price<0)return err('معلومات سم او بشپړ کړئ');if(oid){const old=await env.DB.prepare(`SELECT * FROM orders WHERE id=? AND created_by=? AND status='registered'`).bind(oid,u.id).first();if(!old)return err('د اصلاح اجازه نشته',403);await env.DB.prepare(`UPDATE orders SET product_name=?,customer_phone=?,province=?,quantity=?,address=?,price=? WHERE id=? AND status='registered'`).bind(name,cp,province,qty,address,price,oid).run();return json({ok:true})}await env.DB.prepare(`INSERT INTO orders(id,product_name,customer_phone,province,quantity,address,price,photo_path,status,created_by,created_at) VALUES(?,?,?,?,?,?,?,'','registered',?,?)`).bind(id(),name,cp,province,qty,address,price,u.id,now()).run();return json({ok:true})}
 let m=path.match(/^\/api\/orders\/([^/]+)$/);if(m&&req.method==='DELETE'){const u=await requireUser(req,env);const o=await env.DB.prepare(`SELECT * FROM orders WHERE id=? AND created_by=? AND status='registered'`).bind(m[1],u.id).first();if(!o)return err('لېږل شوی یا تسلیم شوی جنس نه شي ډیلیټ کېدای',403);await env.DB.prepare('DELETE FROM orders WHERE id=?').bind(o.id).run();return json({ok:true})}
 m=path.match(/^\/api\/orders\/([^/]+)\/advance$/);if(m&&req.method==='POST'){const u=await requireUser(req,env);if(u.role!=='dispatcher'||u.status!=='approved')return err('اجازه نشته',403);const o=await env.DB.prepare(`SELECT * FROM orders WHERE id=? AND status='registered'`).bind(m[1]).first();if(!o)return err('آرډر د پروسس وړ نه دی');const st=o.province==='کندهار'?'delivered':'sent';const changed=await env.DB.prepare("UPDATE orders SET status=?,processed_at=? WHERE id=? AND status='registered'").bind(st,now(),o.id).run();if(!changed.meta.changes)return err('آرډر مخکې پروسس شوی',409);return json({status:st})}
 if(path==='/api/stats'){const u=await requireUser(req,env);if(u.status!=='approved')return err('اجازه نشته',403);const key=dayKey(now()),rs=await env.DB.prepare(`SELECT province,status,COUNT(*) AS n,COALESCE(SUM(price),0) AS money FROM orders WHERE date(datetime(processed_at,'-90 minutes'))=? AND processed_at IS NOT NULL AND (?<>'agent' OR created_by=?) GROUP BY province,status`).bind(key,u.role,u.id).all();let a={otherCount:0,otherMoney:0,kandaharCount:0,kandaharMoney:0};for(const o of rs.results){if(o.province==='کندهار'&&o.status==='delivered'){a.kandaharCount+=o.n;a.kandaharMoney+=o.money}else if(o.province!=='کندهار'&&o.status==='sent'){a.otherCount+=o.n;a.otherMoney+=o.money}}return json(a)}
 if(path==='/api/users'){await requireAdmin(req,env);const rs=await env.DB.prepare('SELECT id,full_name,phone,role,status,selfie_path,created_at FROM users ORDER BY created_at DESC').all();return json({users:rs.results})}
 m=path.match(/^\/api\/users\/([^/]+)$/);if(m&&req.method==='PATCH'){await requireAdmin(req,env);const {action}=await req.json();if(!['agent','dispatcher','reject'].includes(action))return err('ناسم عمل');const changed=await env.DB.prepare('UPDATE users SET role=?,status=? WHERE id=? AND role<>?').bind(action==='reject'?'agent':action,action==='reject'?'rejected':'approved',m[1],'admin').run();if(!changed.meta.changes)return err('کاروونکی ونه موندل شو یا اډمین دی',404);if(action==='reject')await env.DB.prepare('DELETE FROM sessions WHERE user_id=?').bind(m[1]).run();return json({ok:true})}
 m=path.match(/^\/api\/users\/([^/]+)\/pin$/);if(m&&req.method==='PATCH'){await requireAdmin(req,env);const {pin}=await req.json();if(!validPin(String(pin)))return err('څلور عددي PIN ولیکئ');const salt=id(),h=await pinHash(String(pin),salt);await env.DB.prepare('UPDATE users SET pin_hash=?,pin_salt=? WHERE id=?').bind(h,salt,m[1]).run();await env.DB.prepare('DELETE FROM sessions WHERE user_id=?').bind(m[1]).run();return json({ok:true})}
 if(path==='/api/report'){const u=await requireUser(req,env);if(u.status!=='approved')return err('اجازه نشته',403);const rs=await env.DB.prepare(`SELECT date(datetime(processed_at,'-90 minutes')) AS key,province,status,COUNT(*) AS n,COALESCE(SUM(price),0) AS money FROM orders WHERE processed_at IS NOT NULL AND (?<>'agent' OR created_by=?) GROUP BY key,province,status ORDER BY key DESC`).bind(u.role,u.id).all(),map=new Map();for(const o of rs.results){if(!map.has(o.key))map.set(o.key,{key:o.key,otherCount:0,otherMoney:0,kandaharCount:0,kandaharMoney:0});const d=map.get(o.key);if(o.province==='کندهار'&&o.status==='delivered'){d.kandaharCount+=o.n;d.kandaharMoney+=o.money}else if(o.province!=='کندهار'&&o.status==='sent'){d.otherCount+=o.n;d.otherMoney+=o.money}}return json({days:[...map.values()]})}
 return err('API ونه موندل شو',404)
}
export async function handleApi(req,env,path){try{return await api(req,env,path)}catch(e){return err(e?.message||'د سرور ستونزه',e?.status||500)}}
