const enc=new TextEncoder();
const json=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json;charset=UTF-8',...headers}});
const err=(m,s=400)=>json({error:m},s);
const id=()=>crypto.randomUUID();
const now=()=>new Date().toISOString();
const b64=a=>btoa(String.fromCharCode(...new Uint8Array(a))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
async function sha(s){return b64(await crypto.subtle.digest('SHA-256',enc.encode(s)))}
async function pinHash(pin,salt,pepper){return sha(`${salt}:${pin}:${pepper}`)}
function cookie(token,max=2592000){return `ifc_session=${token}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=${max}`}
function getCookie(req,n){return (req.headers.get('cookie')||'').split(';').map(x=>x.trim()).find(x=>x.startsWith(n+'='))?.slice(n.length+1)||''}
async function auth(req,env){const t=getCookie(req,'ifc_session');if(!t)return null;const h=await sha(t);return await env.DB.prepare(`SELECT u.* FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>?`).bind(h,now()).first()}
async function requireUser(req,env){const u=await auth(req,env);if(!u||u.status==='rejected')throw {status:401,message:'لومړی حساب ته ننوځئ'};return u}
async function requireAdmin(req,env){const u=await requireUser(req,env);if(u.role!=='admin'||u.status!=='approved')throw {status:403,message:'اجازه نشته'};return u}
async function parseForm(req){try{return await req.formData()}catch(_){throw {status:400,message:'معلومات سم نه دي'}}}
function validPhone(p){return /^07\d{8}$/.test(p||'')}
function validPin(p){return /^\d{4}$/.test(p||'')}
async function putPhoto(env,key,file){if(!file||!file.size)throw {status:400,message:'عکس انتخاب کړئ'};if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw {status:400,message:'یوازې JPG، PNG یا WebP عکس غوره کړئ'};if(file.size>5*1024*1024)throw {status:400,message:'عکس ډېر لوی دی'};await env.PHOTOS.put(key,await file.arrayBuffer(),{httpMetadata:{contentType:file.type||'image/jpeg',cacheControl:'public, max-age=604800'}});return key}
function dayKey(iso){const d=new Date(new Date(iso).getTime()+(270-360)*60000);return `${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,'0')}-${String(d.getUTCDate()).padStart(2,'0')}`}
async function api(req,env,path){
 if(!env.PIN_PEPPER||!env.SETUP_CODE)return err('د سیستم امنیتي تنظیمات نشته',503);
 if(path==='/api/setup'&&req.method==='GET'){const admin=await env.DB.prepare("SELECT id FROM users WHERE role='admin' LIMIT 1").first();return json({ready:!!admin})}
 if(path==='/api/setup'&&req.method==='POST'){const f=await parseForm(req),code=String(f.get('code')||''),name=String(f.get('name')||'').trim(),phone=String(f.get('phone')||''),pin=String(f.get('pin')||''),photo=f.get('photo');if(code!==env.SETUP_CODE)return err('د پیل کوډ ناسم دی',403);if(!validPhone(phone)||!validPin(pin)||!name)return err('نوم، شمېره او PIN سم ولیکئ');if(await env.DB.prepare("SELECT id FROM users WHERE role='admin' LIMIT 1").first())return err('اډمین مخکې جوړ شوی دی',409);const uid=id(),key=`identity/${uid}/profile.jpg`,salt=id(),h=await pinHash(pin,salt,env.PIN_PEPPER);await putPhoto(env,key,photo);try{const result=await env.DB.prepare("INSERT INTO users(id,full_name,phone,pin_hash,pin_salt,role,status,selfie_path,created_at) SELECT ?,?,?,?,?,'admin','approved',?,? WHERE NOT EXISTS(SELECT 1 FROM users WHERE role='admin')").bind(uid,name,phone,h,salt,key,now()).run();if(!result.meta.changes){await env.PHOTOS.delete(key);return err('اډمین مخکې جوړ شوی دی',409)}}catch(e){await env.PHOTOS.delete(key);throw e}return json({ok:true})}

 if(path==='/api/register'&&req.method==='POST'){const f=await parseForm(req),name=String(f.get('name')||'').trim(),phone=String(f.get('phone')||''),pin=String(f.get('pin')||''),photo=f.get('photo');if(!name)return err('بشپړ نوم ولیکئ');if(!validPhone(phone))return err('د موبایل شمېره سمه ولیکئ');if(!validPin(pin))return err('څلور عددي PIN ولیکئ');if(await env.DB.prepare('SELECT id FROM users WHERE phone=?').bind(phone).first())return err('دا موبایل شمېره مخکې ثبت شوې ده');const uid=id(),salt=id(),h=await pinHash(pin,salt,env.PIN_PEPPER),key=`identity/${uid}/profile.jpg`;await putPhoto(env,key,photo);await env.DB.prepare(`INSERT INTO users(id,full_name,phone,pin_hash,pin_salt,role,status,selfie_path,created_at) VALUES(?,?,?,?,?,'agent','pending',?,?)`).bind(uid,name,phone,h,salt,key,now()).run();return json({ok:true})}
 if(path==='/api/login'&&req.method==='POST'){const {phone,pin}=await req.json();if(!validPhone(phone)||!validPin(String(pin)))return err('موبایل شمېره یا PIN ناسم دی',401);const cutoff=new Date(Date.now()-15*60000).toISOString();const attempts=await env.DB.prepare('SELECT COUNT(*) AS n FROM login_attempts WHERE phone=? AND created_at>?').bind(phone,cutoff).first();if(attempts.n>=8)return err('ډېرې هڅې شوې؛ ۱۵ دقیقې وروسته بیا کوښښ وکړئ',429);const u=await env.DB.prepare('SELECT * FROM users WHERE phone=?').bind(phone).first();if(!u||await pinHash(String(pin),u.pin_salt,env.PIN_PEPPER)!==u.pin_hash){await env.DB.prepare('INSERT INTO login_attempts(phone,created_at) VALUES(?,?)').bind(phone,now()).run();return err('موبایل شمېره یا PIN ناسم دی',401)}await env.DB.prepare('DELETE FROM login_attempts WHERE phone=?').bind(phone).run();if(u.status==='rejected')return err('ستاسې حساب بند شوی دی',403);const token=b64(crypto.getRandomValues(new Uint8Array(32))),th=await sha(token),exp=new Date(Date.now()+30*864e5).toISOString();await env.DB.prepare('INSERT INTO sessions(token_hash,user_id,expires_at) VALUES(?,?,?)').bind(th,u.id,exp).run();return json({ok:true},200,{'set-cookie':cookie(token)})}
 if(path==='/api/logout'&&req.method==='POST'){const t=getCookie(req,'ifc_session');if(t)await env.DB.prepare('DELETE FROM sessions WHERE token_hash=?').bind(await sha(t)).run();return json({ok:true},200,{'set-cookie':cookie('',0)})}
 if(path==='/api/me'){const u=await requireUser(req,env);delete u.pin_hash;delete u.pin_salt;return json({profile:u})}
 if(path==='/api/me/photo'&&req.method==='POST'){const u=await requireUser(req,env),f=await parseForm(req),key=`identity/${u.id}/${id()}.jpg`;await putPhoto(env,key,f.get('photo'));try{await env.DB.prepare('UPDATE users SET selfie_path=? WHERE id=?').bind(key,u.id).run()}catch(e){await env.PHOTOS.delete(key);throw e}if(u.selfie_path)await env.PHOTOS.delete(u.selfie_path);return json({photo_path:key})}
 if(path.startsWith('/api/photo/')&&req.method==='GET'){const viewer=await requireUser(req,env);if(viewer.status!=='approved')return err('اجازه نشته',403);const key=decodeURIComponent(path.slice('/api/photo/'.length));if(!/^(identity|orders)\/[a-f0-9-]+\/[a-f0-9-]+\.jpg$/.test(key)&&!/^identity\/[a-f0-9-]+\/profile\.jpg$/.test(key))return err('عکس ونه موندل شو',404);if(viewer.role==='agent'&&!key.startsWith(`identity/${viewer.id}/`)&&!key.startsWith(`orders/${viewer.id}/`))return err('اجازه نشته',403);const o=await env.PHOTOS.get(key);if(!o)return new Response('Not found',{status:404});const h=new Headers();o.writeHttpMetadata(h);h.set('etag',o.httpEtag);return new Response(o.body,{headers:h})}
 if(path==='/api/orders'&&req.method==='GET'){const u=await requireUser(req,env);if(u.status!=='approved')return err('حساب لا نه دی تایید شوی',403);const url=new URL(req.url),off=Math.max(0,Number(url.searchParams.get('offset')||0)),lim=Math.min(50,Math.max(1,Number(url.searchParams.get('limit')||20)));let q,rs;if(u.role==='agent'){q=env.DB.prepare(`SELECT o.*,u.full_name creator_name FROM orders o JOIN users u ON u.id=o.created_by WHERE o.created_by=? ORDER BY o.created_at DESC LIMIT ? OFFSET ?`);rs=await q.bind(u.id,lim+1,off).all()}else{q=env.DB.prepare(`SELECT o.*,u.full_name creator_name FROM orders o JOIN users u ON u.id=o.created_by ORDER BY o.created_at DESC LIMIT ? OFFSET ?`);rs=await q.bind(lim+1,off).all()}return json({orders:rs.results.slice(0,lim),hasMore:rs.results.length>lim})}
 if(path==='/api/orders'&&req.method==='POST'){const u=await requireUser(req,env);if(u.role!=='agent'||u.status!=='approved')return err('یوازې شاګرد جنس ثبتولی شي',403);const f=await parseForm(req),oid=String(f.get('id')||''),name=String(f.get('product_name')||'').trim(),cp=String(f.get('customer_phone')||'').trim(),province=String(f.get('province')||''),qty=Number(f.get('quantity')),address=String(f.get('address')||'').trim(),price=Number(f.get('price')),photo=f.get('photo');if(!name||!cp||!province||!address||!Number.isSafeInteger(qty)||qty<1||!Number.isSafeInteger(price)||price<0)return err('معلومات سم او بشپړ کړئ');if(oid){const old=await env.DB.prepare(`SELECT * FROM orders WHERE id=? AND created_by=? AND status='registered'`).bind(oid,u.id).first();if(!old)return err('د اصلاح اجازه نشته',403);let key=old.photo_path;if(photo&&photo.size){key=`orders/${u.id}/${id()}.jpg`;await putPhoto(env,key,photo);if(old.photo_path)await env.PHOTOS.delete(old.photo_path)}await env.DB.prepare(`UPDATE orders SET product_name=?,customer_phone=?,province=?,quantity=?,address=?,price=?,photo_path=? WHERE id=? AND status='registered'`).bind(name,cp,province,qty,address,price,key,oid).run();return json({ok:true})}if(!photo||!photo.size)return err('د جنس عکس واخلئ');const key=`orders/${u.id}/${id()}.jpg`,newid=id();await putPhoto(env,key,photo);await env.DB.prepare(`INSERT INTO orders(id,product_name,customer_phone,province,quantity,address,price,photo_path,status,created_by,created_at) VALUES(?,?,?,?,?,?,?,?,'registered',?,?)`).bind(newid,name,cp,province,qty,address,price,key,u.id,now()).run();return json({ok:true})}
 let m=path.match(/^\/api\/orders\/([^/]+)$/);if(m&&req.method==='DELETE'){const u=await requireUser(req,env);const o=await env.DB.prepare(`SELECT * FROM orders WHERE id=? AND created_by=? AND status='registered'`).bind(m[1],u.id).first();if(!o)return err('لېږل شوی یا تسلیم شوی جنس نه شي ډیلیټ کېدای',403);await env.DB.prepare('DELETE FROM orders WHERE id=?').bind(o.id).run();if(o.photo_path)await env.PHOTOS.delete(o.photo_path);return json({ok:true})}
 m=path.match(/^\/api\/orders\/([^/]+)\/advance$/);if(m&&req.method==='POST'){const u=await requireUser(req,env);if(u.role!=='dispatcher'||u.status!=='approved')return err('اجازه نشته',403);const o=await env.DB.prepare(`SELECT * FROM orders WHERE id=? AND status='registered'`).bind(m[1]).first();if(!o)return err('آرډر د پروسس وړ نه دی');const st=o.province==='کندهار'?'delivered':'sent';const changed=await env.DB.prepare("UPDATE orders SET status=?,processed_at=? WHERE id=? AND status='registered'").bind(st,now(),o.id).run();if(!changed.meta.changes)return err('آرډر مخکې پروسس شوی',409);return json({status:st})}
 if(path==='/api/stats'){const u=await requireUser(req,env);if(u.status!=='approved')return err('اجازه نشته',403);const key=dayKey(now()),rs=await env.DB.prepare(`SELECT province,status,COUNT(*) AS n,COALESCE(SUM(price),0) AS money FROM orders WHERE date(datetime(processed_at,'-90 minutes'))=? AND processed_at IS NOT NULL AND (?<>'agent' OR created_by=?) GROUP BY province,status`).bind(key,u.role,u.id).all();let a={otherCount:0,otherMoney:0,kandaharCount:0,kandaharMoney:0};for(const o of rs.results){if(o.province==='کندهار'&&o.status==='delivered'){a.kandaharCount+=o.n;a.kandaharMoney+=o.money}else if(o.province!=='کندهار'&&o.status==='sent'){a.otherCount+=o.n;a.otherMoney+=o.money}}return json(a)}
 if(path==='/api/users'){await requireAdmin(req,env);const rs=await env.DB.prepare('SELECT id,full_name,phone,role,status,selfie_path,created_at FROM users ORDER BY created_at DESC').all();return json({users:rs.results})}
 m=path.match(/^\/api\/users\/([^/]+)$/);if(m&&req.method==='PATCH'){await requireAdmin(req,env);const {action}=await req.json();if(!['agent','dispatcher','reject'].includes(action))return err('ناسم عمل');const changed=await env.DB.prepare('UPDATE users SET role=?,status=? WHERE id=? AND role<>?').bind(action==='reject'?'agent':action,action==='reject'?'rejected':'approved',m[1],'admin').run();if(!changed.meta.changes)return err('کاروونکی ونه موندل شو یا اډمین دی',404);if(action==='reject')await env.DB.prepare('DELETE FROM sessions WHERE user_id=?').bind(m[1]).run();return json({ok:true})}
 m=path.match(/^\/api\/users\/([^/]+)\/pin$/);if(m&&req.method==='PATCH'){await requireAdmin(req,env);const {pin}=await req.json();if(!validPin(String(pin)))return err('څلور عددي PIN ولیکئ');const salt=id(),h=await pinHash(String(pin),salt,env.PIN_PEPPER);await env.DB.prepare('UPDATE users SET pin_hash=?,pin_salt=? WHERE id=?').bind(h,salt,m[1]).run();await env.DB.prepare('DELETE FROM sessions WHERE user_id=?').bind(m[1]).run();return json({ok:true})}
 if(path==='/api/report'){const u=await requireUser(req,env);if(u.status!=='approved')return err('اجازه نشته',403);const rs=await env.DB.prepare(`SELECT date(datetime(processed_at,'-90 minutes')) AS key,province,status,COUNT(*) AS n,COALESCE(SUM(price),0) AS money FROM orders WHERE processed_at IS NOT NULL AND (?<>'agent' OR created_by=?) GROUP BY key,province,status ORDER BY key DESC`).bind(u.role,u.id).all(),map=new Map();for(const o of rs.results){if(!map.has(o.key))map.set(o.key,{key:o.key,otherCount:0,otherMoney:0,kandaharCount:0,kandaharMoney:0});const d=map.get(o.key);if(o.province==='کندهار'&&o.status==='delivered'){d.kandaharCount+=o.n;d.kandaharMoney+=o.money}else if(o.province!=='کندهار'&&o.status==='sent'){d.otherCount+=o.n;d.otherMoney+=o.money}}return json({days:[...map.values()]})}
 return err('API ونه موندل شو',404)
}
export async function handleApi(req,env,path){try{return await api(req,env,path)}catch(e){return err(e?.message||'د سرور ستونزه',e?.status||500)}}
